# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: cyberchief-security-scanner@1
  inputs:
    scanType: 'web'
    scope: 'reconnaissance'
    apiEndpoint: 'http://localhost:8000/api/137/1173/automated-tests/'
    failOnHighVulnerabilities: true
    failOnHighAndMediumVulnerabilities: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
